# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.0.0
group=com.rempler.jagahm
java_version=17

# Common
minecraft_version=1.20.4
mod_name=JAGAHM
mod_author=Rempler
mod_id=jagahm
license=ARR
credits=
description=This mod has no description.
minecraft_version_range=[1.20.4, 1.21)

# Fabric
fabric_version=0.97.2+1.20.4
fabric_loader_version=0.16.14

# Forge
forge_version=49.2.0
forge_loader_version_range=[49,)
forge_version_range=[49,)

# NeoForge
neoforge_version=20.4.248
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
