plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
   //runtimeOnly "mezz.jei:jei-1.21.1-neoforge:19.17.0.196"
   //runtimeOnly "curse.maven:top-245211:5502323"

    //implementation 'curse.maven:agricraft-225635:3883933'
    //runtimeOnly 'curse.maven:infinitylib-251396:3883932'

    //runtimeOnly 'com.blakebr0.cucumber:Cucumber:1.21.1-8.0.5'
    //implementation 'com.blakebr0.mysticalagriculture:MysticalAgriculture:1.21.1-8.0.6'
}

repositories {
    maven { url "https://repo.glaremasters.me/repository/public/" }
    maven{
        url = 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url 'https://maven.blakesmods.com'
        content {
            includeGroup "com.blakebr0.cucumber"
            includeGroup "com.blakebr0.mysticalagriculture"
        }
    }
    maven {
        url 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }
}

tasks.register('idePostSync') {
}

sourceSets.main.resources { srcDir 'src/generated/resources' }