plugins {
    id 'multiloader-loader'
    id 'net.neoforged.gradle.userdev' version '7.0.107'
}

// Automatically enable neoforge AccessTransformers if the file exists
// This location is hardcoded in FML and can not be changed.
// https://github.com/neoforged/FancyModLoader/blob/a952595eaaddd571fbc53f43847680b00894e0c1/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java#L118
def at = file('src/main/resources/META-INF/accesstransformer.cfg')
if (at.exists()) {
    minecraft.accessTransformers.file at
}
runs {
    configureEach {
        modSource project.sourceSets.main
    }
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }
    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven{
        url = 'https://cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url 'https://maven.blakesmods.com'
        content {
            includeGroup "com.blakebr0.cucumber"
            includeGroup "com.blakebr0.mysticalagriculture"
        }
    }
    maven {
        url 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }
}
dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    //runtimeOnly "mezz.jei:jei-1.20.4-neoforge:19.17.0.196"
    //runtimeOnly "curse.maven:top-245211:5502323"

    implementation 'curse.maven:agricraft-225635:5465322'
    //runtimeOnly 'curse.maven:infinitylib-251396:3883932'
    runtimeOnly 'curse.maven:resourcefulconfig-714059:6223995'

    //runtimeOnly 'com.blakebr0.cucumber:Cucumber:1.20.4-8.0.5'
    //implementation 'com.blakebr0.mysticalagriculture:MysticalAgriculture:1.20.4-8.0.6'
}